In [3]:
import numpy as np
a = np.arange(5)
a

array([0, 1, 2, 3, 4])

In [5]:
T = np.diag(a)
T

array([[0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 2, 0, 0],
       [0, 0, 0, 3, 0],
       [0, 0, 0, 0, 4]])

In [11]:
T2 = np.diag(np.arange(-4, 1))
T2

array([[-4,  0,  0,  0,  0],
       [ 0, -3,  0,  0,  0],
       [ 0,  0, -2,  0,  0],
       [ 0,  0,  0, -1,  0],
       [ 0,  0,  0,  0,  0]])

In [28]:
T2 = np.vstack((np.array([0]*5), T2[:4]))
T2

array([[ 0,  0,  0,  0,  0],
       [-4,  0,  0,  0,  0],
       [ 0, -3,  0,  0,  0],
       [ 0,  0, -2,  0,  0],
       [ 0,  0,  0, -1,  0]])

In [29]:
T + T2

array([[ 0,  0,  0,  0,  0],
       [-4,  1,  0,  0,  0],
       [ 0, -3,  2,  0,  0],
       [ 0,  0, -2,  3,  0],
       [ 0,  0,  0, -1,  4]])